### ISSUE TITLE
Can you add "Sound Blaster X-FI MB5" support in your drivers ?

### ISSUE THREAD

**Issue by Hiko14th** [AlanFinotty/AAFOptimusDCHAudio-Realtek#10]
yeah because all creative products like 360,720 and cinema 5 are total garbage when it comes to compare with x-fi mb5...

**Comment by SEGAINDEED** [comment]
i agree. i want beats audio as well both of these will be a great blessing.

**Comment by AlanFinotty** [comment]
In progress. The next release will already have the X-Fi MB5 available

**Comment by epman100** [comment]
> i agree. i want beats audio as well both of these will be a great blessing.

beats audio is specific to HP/Compaq systems only (uses SRS underneath the surface), so that won't happen

but definitely X-Fi MB5 should be added in the next version

**Comment by AlanFinotty** [comment]
Done!
