### ISSUE TITLE
DTS unbound not working

### ISSUE THREAD

**Issue by Harsh4370** [AlanFinotty/AAFOptimusDCHAudio-Realtek#14]
DTS unbound does not have DTS Headphone X licence. 

Please make crack of Dolby for headphones or dts Headphone X

**Comment by umarizulkifli** [comment]
Turn off internet during installation

**Comment by Harsh4370** [comment]
Thank brother!!
It worked 😃

**Comment by Harsh4370** [comment]
Brother it showed licenced 1 time but when I uninstall and reinstall it even my internet is off it is not showing licenced it showed the original price
