### ISSUE TITLE
Not Working on ALC897 Codec  - MSI PRO Z690-A WIFI

### ISSUE THREAD

**Issue by Riaulo** [AlanFinotty/AAFOptimusDCHAudio-Realtek#18]
Even if the installation takes place without any error warnings, the audio drivers are not installed.

**Comment by wiesshund** [comment]
I dont have that board but i do have that chipset
Did you uninstall everything, and then use the recommended driver store cleaning tool and clean out everything related to realtec and AAF etc.

Open windows store a sec, and set it to NOT auto update any apps

Then disconnect from internet and reboot, so windows cant find anything but it's own generic hd audio drivers.

Then install Alan's driver set again, and reboot when it is finished

It should come up working for you after that i think?

I didnt install the a-volute or creative stuff at all, not the dts X, just the atmos as it is sometimes nice for movies
and then of course the realtec drivers, and the dd live and dts live and the very top intel option for whatever use it is.
and the very bottom realtec apo option

**Comment by Riaulo** [comment]
I was able to install by forcing the drivers from the installation folder. (AAFOptimusDCHAudioPack\Driver64)
