### ISSUE TITLE
Use with S/PDIF

### ISSUE THREAD

**Issue by Bercraft** [AlanFinotty/AAFOptimusDCHAudio-Realtek#4]
Hello is it possible to make this audio mod compatible with S/PDIF audio, like enabling DTS interactive or dolby digital thank you.
Moreover would be nice to be able to use dts ultra or dolby atmos with the S/PDIF, because with your package they only work via jack.
Tank you for your awesome work

**Comment by epman100** [comment]
it depends if your motherboard has an actual SPDIF digital audio out port at the back (either coaxial or optical)

**Comment by Bercraft** [comment]
it has, it was a windows 11 bug solved with a clean installation at the end thank you
