### ISSUE TITLE
RTASIOCP is missing

### ISSUE THREAD

**Issue by VermillionH** [AlanFinotty/AAFOptimusDCHAudio-Realtek#47]
Can't install because RTASIOCP.dll is missing 
![image](https://github.com/AlanFinotty/AAFOptimusDCHAudio-Realtek/assets/119064485/cf3cbced-7c31-44e9-ac45-8795b7e4f94f)

**Comment by Aeropro4** [comment]
Yeah Same in mine aswell was going to post issue

**Comment by AlanFinotty** [comment]
Fixed in Last Release

**Comment by epman100** [comment]
time to close this issue once it's "fixed" or resolved
