### ISSUE TITLE
Why this program installed a root certicificate in my computer?

### ISSUE THREAD

**Issue by gszshdzz** [AlanFinotty/AAFOptimusDCHAudio-Realtek#65]
![image](https://github.com/AlanFinotty/AAFOptimusDCHAudio-Realtek/assets/68946978/ec1d2326-776f-4fa0-b251-88ce30145aa6)

**Comment by PtvKeegan** [comment]
I'm concerned about that too

**Comment by gszshdzz** [comment]
> I'm concerned about that too

Maybe it is for the hacked dts sound unbound application (?)

**Comment by AlanFinotty** [comment]
This certificate is used to ensure smooth installation of driver packages, which are digitally signed using the same certificate.

**Comment by gszshdzz** [comment]
> This certificate is used to ensure smooth installation of driver packages, which are digitally signed using the same certificate. Its use was never intended to insert viruses into users' computers.

Thank you! But I think you can add an explaination in the installer
